// AUTO-GENERATED by scripts/seal-runtime.js — do not edit.
// Dev fallback only (real packs overwrite this file each seal).
namespace OugiHostApp
{
    internal static class SealSecrets
    {
        public const string Passphrase = "OugiHost.Runtime.Seal.v1.dev-only";
    }
}
